# Convert MSVC runtime library string to Meson flag and append to var_name
function(msvc_runtime_library_to_meson_flags var_name runtime_library)
    if (runtime_library STREQUAL "MultiThreaded")
        set("${var_name}" ${${var_name}} -Db_vscrt=mt PARENT_SCOPE)
    elseif (runtime_library STREQUAL "MultiThreadedDLL")
        set("${var_name}" ${${var_name}} -Db_vscrt=md PARENT_SCOPE)
    elseif(runtime_library STREQUAL "MultiThreadedDebug")
        set("${var_name}" ${${var_name}} -Db_vscrt=mtd PARENT_SCOPE)
    elseif(runtime_library STREQUAL "MultiThreadedDebugDLL")
        set("${var_name}" ${${var_name}} -Db_vscrt=mdd PARENT_SCOPE)
    else ()
        show_fatal_error("Unknown MSVC runtime library: '${runtime_library}'")
    endif ()
endfunction()